server:
  servlet:
    context-path: /dlthotel

spring:
  profiles:
    active: dev

# 是否开启文档功能
apidoc: true

task:
  pool:
    corePoolSize: 20
    maxPoolSize: 40
    keepAliveSeconds: 300
    queueCapacity: 50
