server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://47.106.207.69:3306/dlt_hotel?useUnicode=true&characterEncoding=UTF-8&useSSL=true
    username: panxl
    password: 123456pxl
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      max-active: 20
      min-idle: 5
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 100
      max-open-prepared-statements: 20
      validation-query: SELECT 1 FROM DUAL
      validation-query-timeout: 30
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      filters: stat,wall,log4j
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 2000
      web-stat-filter:
        enable: true
      stat-view-servlet:
        enabled: true
        #druid控制台的用户名和密码
        login-username: druid_admin
        login-password: 123456
  redis:
    database: 0
    host: 47.106.207.69
    password: 123456pxl
    port: 6379
    timeout: 30000       # 连接超时时间 单位 ms（毫秒）
    pool:
      max-idle: 8       # 连接池中的最大空闲连接，默认值也是8
      min-idle: 2       # 连接池中的最小空闲连接，默认值也是0
      max-active: 8     # 如果赋值为-1，则表示不限制；如果pool已经分配了maxActive个jedis实例，则此时pool的状态为exhausted(耗尽)。
      max-wait: -1      # 等待可用连接的最大时间，单位毫秒，默认值为-1，表示永不超时。如果超过等待时间，则直接抛出
mybatis-plus:
  mapperLocations: classpath*:com/handinglian/*/mapperxml/*.xml
  typeAliasesPackage: com.handinglian.*.entity;com.apidoc.*.entity

file:
  location: D:/file/

download:
  url: /download/file/
